<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-06-02T06:11:02+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'UTC',
    'api_keys' => [
        'google' => [
            'maps' => '',
        ],
    ],
];
