<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-06-30T06:54:25+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.5.2',
    'version_db_installed' => '20190925072210',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1591078262,
        'do_page_reindex_check' => false,
        'latest_version' => '8.5.2',
    ],
    'calendar' => [
        'topic_attribute' => 'event_categories',
    ],
    'seo' => [
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => true,
    ],
    'cache' => [
        'clear' => [
            'thumbnails' => true,
        ],
    ],
];
