<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-06-02T06:09:04+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'LocalC5',
        ],
    ],
];
