<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-08-14T07:23:35+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.seo.tracking.code.footer
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'LocalC5',
            'seo' => [
                'canonical_url' => '',
                'canonical_url_alternative' => '',
                'canonical_tag' => [
                    'enabled' => true,
                ],
                'tracking' => [
                    'code' => [
                        'header' => '<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':
      new Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=
      \'https://www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);
      })(window,document,\'script\',\'dataLayer\',\'GTM-M649WJD\');</script>',
                        'footer' => '<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-M649WJD"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>',
                    ],
                ],
            ],
        ],
    ],
];
